@startuml
title Lesson4-9-5

start

:「西暦の年を入力してください。」を表示;
:西暦の年を入力しyearに代入/
if (year %4 == 0 and year %100 != 0 or year %400 == 0) then (はい)
   :year+「年はうるう年です。」を表示;
else (いいえ)
   :year+「年はうるう年ではありません。」を表示;
endif

end

@enduml